-- KYO Sushi - esquema inicial Supabase
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  is_admin boolean not null default false,
  reward_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id text primary key,
  name text not null,
  short_name text not null,
  address text not null,
  phone text,
  eta text,
  active boolean not null default true
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  parent_id uuid references public.categories(id) on delete cascade
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  category_id uuid references public.categories(id) on delete set null,
  subcategory_id uuid references public.categories(id) on delete set null,
  image_url text,
  featured boolean not null default false,
  spicy boolean not null default false,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Dirección',
  address_line text not null,
  notes text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid not null references public.profiles(id) on delete restrict,
  branch_id text not null references public.branches(id),
  fulfillment_type text not null check (fulfillment_type in ('delivery','pickup')),
  delivery_address text,
  delivery_notes text,
  payment_method text not null default 'cash',
  status text not null default 'received' check (status in ('received','accepted','preparing','ready','on_the_way','delivered','cancelled')),
  subtotal numeric(10,2) not null,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  rewards_awarded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity > 0)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    nullif(new.raw_user_meta_data->>'phone','')
  )
  on conflict (id) do update
    set full_name=excluded.full_name,
        phone=coalesce(excluded.phone, public.profiles.phone),
        updated_at=now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id = uid and p.is_admin = true);
$$;

create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_delivery_address text,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2) := 0;
  v_delivery_fee numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if p_fulfillment_type = 'delivery' and coalesce(trim(p_delivery_address),'') = '' then raise exception 'Falta dirección de entrega'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb)) = 0 then raise exception 'El carrito está vacío'; end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p
      where p.id = (v_item->>'product_id')::uuid and p.available = true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;
    v_subtotal := v_subtotal + (v_product.price * v_qty);
  end loop;

  v_delivery_fee := case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total := v_subtotal + v_delivery_fee;

  insert into public.orders(user_id,branch_id,fulfillment_type,delivery_address,delivery_notes,payment_method,subtotal,delivery_fee,total)
  values(v_user,p_branch_id,p_fulfillment_type,p_delivery_address,p_delivery_notes,p_payment_method,v_subtotal,v_delivery_fee,v_total)
  returning public.orders.id, public.orders.order_number into v_order_id, v_order_number;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p where p.id = (v_item->>'product_id')::uuid;
    insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
    values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty);
  end loop;

  return query select v_order_id, v_order_number, v_total;
end;
$$;

revoke all on function public.create_order(text,text,text,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,text,text,text,jsonb) to authenticated;

create or replace function public.award_rewards_on_delivery()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.status = 'delivered' and old.status is distinct from 'delivered' and new.rewards_awarded = false then
    update public.profiles
      set reward_points = reward_points + floor(new.subtotal)::int,
          updated_at = now()
      where id = new.user_id;
    new.rewards_awarded := true;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists orders_award_rewards on public.orders;
create trigger orders_award_rewards
before update on public.orders
for each row execute procedure public.award_rewards_on_delivery();

alter table public.profiles enable row level security;
alter table public.branches enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Lectura pública del catálogo
create policy "branches public read" on public.branches for select using (active = true or public.is_admin(auth.uid()));
create policy "categories public read" on public.categories for select using (active = true or public.is_admin(auth.uid()));
create policy "products public read" on public.products for select using (available = true or public.is_admin(auth.uid()));

-- Perfil
create policy "profile own read" on public.profiles for select using (auth.uid() = id or public.is_admin(auth.uid()));
create policy "profile own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and is_admin = false);
create policy "admins manage profiles" on public.profiles for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Direcciones
create policy "addresses own select" on public.addresses for select using (auth.uid() = user_id or public.is_admin(auth.uid()));
create policy "addresses own insert" on public.addresses for insert with check (auth.uid() = user_id);
create policy "addresses own update" on public.addresses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "addresses own delete" on public.addresses for delete using (auth.uid() = user_id);

-- Pedidos
create policy "orders own select" on public.orders for select using (auth.uid() = user_id or public.is_admin(auth.uid()));
create policy "admins update orders" on public.orders for update using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "order items own select" on public.order_items for select using (
  exists(select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin(auth.uid())))
);

-- Admin catálogo
create policy "admins manage branches" on public.branches for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins manage categories" on public.categories for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins manage products" on public.products for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Storage público para fotos del menú
insert into storage.buckets (id, name, public)
values ('menu-images','menu-images',true)
on conflict (id) do update set public = true;

create policy "menu images public read" on storage.objects for select using (bucket_id = 'menu-images');
create policy "admins upload menu images" on storage.objects for insert with check (bucket_id = 'menu-images' and public.is_admin(auth.uid()));
create policy "admins update menu images" on storage.objects for update using (bucket_id = 'menu-images' and public.is_admin(auth.uid()));
create policy "admins delete menu images" on storage.objects for delete using (bucket_id = 'menu-images' and public.is_admin(auth.uid()));


-- Habilita cambios de pedidos en Realtime para el panel.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- Sucursales
insert into public.branches (id,name,short_name,address,phone,eta) values
('zakia','KYO Zákia','Zákia','Plaza UNITY, local 103 PB, Zákia.','442 890 3797','35–50 min'),
('milenio','KYO Milenio','Milenio','Plaza UBIKA Milenio, local 112, Milenio III.','442 283 4928','35–50 min')
on conflict (id) do update set name=excluded.name, short_name=excluded.short_name, address=excluded.address, phone=excluded.phone, eta=excluded.eta;

insert into public.categories(name,slug,sort_order) values
('Entradas','entradas',10),('Kushiagues','kushiagues',20),('Sopas','sopas',30),('Ramen','ramen',40),('Poke Bowl','poke-bowl',50),('Rollos','rollos',60),('Arroz','arroz',70),('Postres','postres',80)
on conflict (slug) do update set name=excluded.name, sort_order=excluded.sort_order;

-- Subcategorías iniciales de Rollos.
with parent as (select id from public.categories where slug='rollos' limit 1)
insert into public.categories(name,slug,sort_order,active,parent_id)
select v.name,v.slug,v.sort_order,true,parent.id
from parent cross join (values ('Clásicos','rollos-clasicos',10),('Tempurizados','rollos-tempurizados',20),('Empanizados','rollos-empanizados',30),('Especiales','rollos-especiales',40)) v(name,slug,sort_order)
on conflict (slug) do update set name=excluded.name,sort_order=excluded.sort_order,parent_id=excluded.parent_id;

-- 20 productos demo del menú KYO 2026. Las imágenes locales se sirven desde Vercel;
-- cuando el admin suba una nueva foto, image_url se reemplaza por la URL de Supabase Storage.
with seed(slug,name,cat,price,description,image_url,featured,spicy,sort_order) as (values
('edamames','Edamames','entradas',98,'150 g · Al vapor, asados con mantequilla y soya o spicy lemon.','/assets/menu/edamames.jpg',true,false,10),
('spring-rolls','Spring Rolls','entradas',92,'4 piezas · Rellenos de vegetales, acompañados de salsa agridulce.','/assets/menu/spring-rolls.jpg',true,false,20),
('gyozas','Gyozas de cerdo','entradas',104,'5 piezas · Empanadillas fritas de cerdo con vegetales, acompañadas de salsa spicy ponzu.','/assets/menu/gyozas.jpg',false,false,30),
('rokka','Camarones Rokka','entradas',168,'Camarón tempura, mayo chipotle, cebollín y aguacate sobre cama de ensalada.','/assets/menu/rokka.jpg',true,true,40),
('karaague','Chicken Karaague','entradas',112,'Pechuga marinada en soya, ajo y jengibre, con mayo chipotle y limón.','/assets/menu/karaague.jpg',false,false,50),
('tempura-verduras','Tempura de verduras','entradas',116,'4 piezas · Verduras de temporada tempurizadas.','/assets/menu/tempura-verduras.jpg',false,false,60),
('kushi-queso','Kushiague de queso manchego','kushiagues',106,'2 piezas · Brochetas empanizadas acompañadas de salsa kushiague.','/assets/menu/kushi-queso.jpg',false,false,70),
('misoshiro','Misoshiro','sopas',78,'225 ml · Fondo miso, harusame, wakame, cebollín y tofu.','/assets/menu/misoshiro.jpg',false,false,80),
('pork-belly-ramen','Pork Belly Ramen','ramen',206,'Pasta ramen, pork belly teriyaki, naruto, verduras, huevo, nori y fondo tonkotsu.','/assets/menu/pork-belly-ramen.jpg',true,false,90),
('tantan-ramen','Tantan Ramen','ramen',218,'Pasta ramen, carne de cerdo picante, chile tempura, huevo, espinaca y fondo tonkotsu.','/assets/menu/tantan-ramen.jpg',false,true,100),
('ebi-crispy-ramen','Ebi Crispy Ramen','ramen',236,'Pasta ramen, camarones crujientes, cebollín, huevo, jitomate, chilli oil y tonkotsu.','/assets/menu/ebi-crispy-ramen.jpg',true,true,110),
('sunset','Sunset','poke-bowl',196,'320 g · Salmón, atún, pescado blanco, aguacate, cebollín y mayo sriracha.','/assets/menu/sunset.jpg',false,false,120),
('tokio-bacon','Tokio Bacon','poke-bowl',186,'320 g · Salmón, tocino ahumado, aguacate, queso fila, pepino y mayo habanero.','/assets/menu/tokio-bacon.jpg',false,false,130),
('samurai','Samurai','poke-bowl',182,'320 g · Camarones rokka, mango, col morada, aguacate y mayo chipotle.','/assets/menu/samurai.jpg',false,false,140),
('spicy-tuna-roll','Spicy Tuna Roll','rollos',154,'10 piezas · Tempurizado, nori, salsa de anguila, cebollín, aguacate y atún spicy.','/assets/menu/spicy-tuna-roll.jpg',true,true,150),
('tampico-roll','Tampico Roll','rollos',148,'10 piezas · Empanizado, tampico, salsa kushiague, aguacate y pepino.','/assets/menu/tampico-roll.jpg',false,false,160),
('philly-roll','Philly Roll','rollos',162,'10 piezas · Empanizado, salsa de anguila, salmón, pepino y queso.','/assets/menu/philly-roll.jpg',false,false,170),
('crunch-roll','Crunch Roll','rollos',172,'10 piezas · Salmón, mayo chipotle, kakiage, queso crema y aguacate.','/assets/menu/crunch-roll.jpg',false,false,180),
('gohan-kyo','Gohan Kyo','arroz',108,'320 g · Gohan, tampico, aguacate, mango, kanikama tempura, chipotle y anguila.','/assets/menu/gohan-kyo.jpg',false,false,190),
('cheesecake-japones','Cheese Cake Japonés','postres',126,'Individual · Con helado de vainilla y salsa de frutos rojos.','/assets/menu/cheesecake-japones.jpg',false,false,200)
)
insert into public.products(slug,name,category_id,price,description,image_url,featured,spicy,sort_order)
select s.slug,s.name,c.id,s.price,s.description,s.image_url,s.featured,s.spicy,s.sort_order
from seed s join public.categories c on c.slug=s.cat
on conflict (slug) do update set
name=excluded.name, category_id=excluded.category_id, price=excluded.price, description=excluded.description,
image_url=excluded.image_url, featured=excluded.featured, spicy=excluded.spicy, sort_order=excluded.sort_order;

update public.products p set subcategory_id=c.id from public.categories c where c.slug='rollos-tempurizados' and p.slug='spicy-tuna-roll';
update public.products p set subcategory_id=c.id from public.categories c where c.slug='rollos-empanizados' and p.slug in ('tampico-roll','philly-roll');
update public.products p set subcategory_id=c.id from public.categories c where c.slug='rollos-especiales' and p.slug='crunch-roll';

-- IMPORTANTE: crea el usuario administrador en Authentication > Users y después ejecuta:
-- update public.profiles set is_admin = true where id = (select id from auth.users where email = 'admin@tudominio.com');

-- ===== KYO v5: direcciones completas, modo cocina y flujo directo a preparación =====
alter table public.profiles add column if not exists kitchen_branch text;

do $$ begin
  alter table public.profiles add constraint profiles_kitchen_branch_check check (kitchen_branch is null or kitchen_branch in ('zakia','milenio'));
exception when duplicate_object then null; end $$;

alter table public.addresses add column if not exists street text;
alter table public.addresses add column if not exists exterior_number text;
alter table public.addresses add column if not exists interior_number text;
alter table public.addresses add column if not exists neighborhood text;
alter table public.addresses add column if not exists postal_code text;
alter table public.addresses add column if not exists branch_id text;

update public.addresses set street = coalesce(street,address_line) where street is null;
update public.addresses set branch_id = coalesce(branch_id,'zakia') where branch_id is null;

do $$ begin
  alter table public.addresses add constraint addresses_branch_fk foreign key (branch_id) references public.branches(id);
exception when duplicate_object then null; end $$;

alter table public.orders add column if not exists delivery_reference text;
alter table public.orders alter column status set default 'preparing';

create or replace function public.is_kitchen_for_branch(uid uuid, p_branch text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = uid and p.kitchen_branch = p_branch
  );
$$;

drop policy if exists "kitchen orders select" on public.orders;
create policy "kitchen orders select" on public.orders for select
using (public.is_kitchen_for_branch(auth.uid(), branch_id));

drop policy if exists "kitchen orders update" on public.orders;
create policy "kitchen orders update" on public.orders for update
using (public.is_kitchen_for_branch(auth.uid(), branch_id))
with check (public.is_kitchen_for_branch(auth.uid(), branch_id));

drop policy if exists "kitchen order items select" on public.order_items;
create policy "kitchen order items select" on public.order_items for select using (
  exists(
    select 1 from public.orders o
    where o.id = order_id and public.is_kitchen_for_branch(auth.uid(), o.branch_id)
  )
);

drop policy if exists "kitchen customer profile read" on public.profiles;
create policy "kitchen customer profile read" on public.profiles for select using (
  exists(
    select 1 from public.orders o
    where o.user_id = profiles.id and public.is_kitchen_for_branch(auth.uid(), o.branch_id)
  )
);

-- Nueva versión segura de create_order: la sucursal de delivery se obtiene de la dirección guardada.
create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_address_id uuid,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2) := 0;
  v_delivery_fee numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_address public.addresses%rowtype;
  v_branch_id text;
  v_address_text text;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb)) = 0 then raise exception 'El carrito está vacío'; end if;

  if p_fulfillment_type = 'delivery' then
    if p_address_id is null then raise exception 'Falta dirección de entrega'; end if;
    select a.* into v_address from public.addresses a where a.id = p_address_id and a.user_id = v_user;
    if not found then raise exception 'Dirección inválida'; end if;
    v_branch_id := v_address.branch_id;
    v_address_text := concat_ws(', ',
      nullif(trim(coalesce(v_address.street,v_address.address_line)),''),
      case when nullif(trim(coalesce(v_address.exterior_number,'')),'') is not null then '#'||trim(v_address.exterior_number) end,
      case when nullif(trim(coalesce(v_address.interior_number,'')),'') is not null then 'Int. '||trim(v_address.interior_number) end,
      nullif(trim(coalesce(v_address.neighborhood,'')),''),
      case when nullif(trim(coalesce(v_address.postal_code,'')),'') is not null then 'CP '||trim(v_address.postal_code) end
    );
  else
    if not exists(select 1 from public.branches b where b.id = p_branch_id and b.active = true) then raise exception 'Sucursal inválida'; end if;
    v_branch_id := p_branch_id;
    v_address_text := null;
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p
      where p.id = (v_item->>'product_id')::uuid and p.available = true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;
    v_subtotal := v_subtotal + (v_product.price * v_qty);
  end loop;

  v_delivery_fee := case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total := v_subtotal + v_delivery_fee;

  insert into public.orders(
    user_id,branch_id,fulfillment_type,delivery_address,delivery_reference,
    delivery_notes,payment_method,status,subtotal,delivery_fee,total
  ) values(
    v_user,v_branch_id,p_fulfillment_type,v_address_text,
    case when p_fulfillment_type='delivery' then v_address.notes else null end,
    p_delivery_notes,p_payment_method,'preparing',v_subtotal,v_delivery_fee,v_total
  )
  returning public.orders.id, public.orders.order_number into v_order_id, v_order_number;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p where p.id = (v_item->>'product_id')::uuid;
    insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
    values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty);
  end loop;

  return query select v_order_id, v_order_number, v_total;
end;
$$;

revoke all on function public.create_order(text,text,uuid,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,uuid,text,text,jsonb) to authenticated;

-- Cuentas de cocina: créalas primero en Authentication > Users y después ejecuta estas líneas.
-- update public.profiles set kitchen_branch='zakia' where id=(select id from auth.users where email='zakia@kyosushi.mx');
-- update public.profiles set kitchen_branch='milenio' where id=(select id from auth.users where email='milenio@kyosushi.mx');

-- ===== v6: Rewards canjeables y tarjeta de 6 pedidos =====
alter table public.profiles add column if not exists reward_order_stamps integer not null default 0;
update public.products set name='4 Spring Rolls' where slug='spring-rolls';
create table if not exists public.reward_vouchers (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
  reward_type text not null check (reward_type in ('spring_rolls','free_roll')),
  status text not null default 'available' check (status in ('available','redeemed','expired')),
  created_at timestamptz not null default now(), redeemed_at timestamptz
);
alter table public.reward_vouchers enable row level security;
drop policy if exists "reward vouchers own select" on public.reward_vouchers;
create policy "reward vouchers own select" on public.reward_vouchers for select using (auth.uid()=user_id or public.is_admin(auth.uid()));
drop policy if exists "admins manage reward vouchers" on public.reward_vouchers;
create policy "admins manage reward vouchers" on public.reward_vouchers for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
grant select on public.reward_vouchers to authenticated;
revoke update(reward_points,reward_order_stamps,is_admin,kitchen_branch) on public.profiles from authenticated;
create or replace function public.award_rewards_on_delivery() returns trigger language plpgsql security definer set search_path=public as $$ begin
  if new.status='delivered' and old.status is distinct from 'delivered' and new.rewards_awarded=false then
    update public.profiles set reward_points=reward_points+floor(new.subtotal)::int,reward_order_stamps=reward_order_stamps+1 where id=new.user_id;
    new.rewards_awarded:=true;
  end if; return new;
end; $$;
create or replace function public.redeem_spring_rolls_reward() returns uuid language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid();v_id uuid;begin
  if v_user is null then raise exception 'Debes iniciar sesión';end if;
  update public.profiles set reward_points=reward_points-250 where id=v_user and reward_points>=250;
  if not found then raise exception 'No tienes 250 puntos disponibles';end if;
  insert into public.reward_vouchers(user_id,reward_type) values(v_user,'spring_rolls') returning id into v_id;return v_id;
end; $$;
create or replace function public.redeem_six_orders_reward() returns uuid language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid();v_id uuid;begin
  if v_user is null then raise exception 'Debes iniciar sesión';end if;
  update public.profiles set reward_order_stamps=reward_order_stamps-6 where id=v_user and reward_order_stamps>=6;
  if not found then raise exception 'Aún no completas 6 pedidos';end if;
  insert into public.reward_vouchers(user_id,reward_type) values(v_user,'free_roll') returning id into v_id;return v_id;
end; $$;
revoke all on function public.redeem_spring_rolls_reward() from public;
revoke all on function public.redeem_six_orders_reward() from public;
grant execute on function public.redeem_spring_rolls_reward() to authenticated;
grant execute on function public.redeem_six_orders_reward() to authenticated;

-- ===== v7: rewards directos al carrito =====
-- En instalaciones nuevas esta redefinición permite enviar reward_voucher_id dentro de p_items.
-- KYO v7: permite usar un voucher de 4 Spring Rolls directamente dentro del carrito.
-- Ejecuta UNA VEZ en Supabase > SQL Editor sobre la base actual.

create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_address_id uuid,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2):=0;
  v_delivery_fee numeric(10,2):=0;
  v_total numeric(10,2):=0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_address public.addresses%rowtype;
  v_branch_id text;
  v_address_text text;
  v_voucher_id uuid;
  v_voucher public.reward_vouchers%rowtype;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'El carrito está vacío'; end if;

  if p_fulfillment_type='delivery' then
    if p_address_id is null then raise exception 'Falta dirección de entrega'; end if;
    select a.* into v_address from public.addresses a where a.id=p_address_id and a.user_id=v_user;
    if not found then raise exception 'Dirección inválida'; end if;
    v_branch_id:=v_address.branch_id;
    v_address_text:=concat_ws(', ',
      nullif(trim(coalesce(v_address.street,v_address.address_line)),''),
      case when nullif(trim(coalesce(v_address.exterior_number,'')),'') is not null then '#'||trim(v_address.exterior_number) end,
      case when nullif(trim(coalesce(v_address.interior_number,'')),'') is not null then 'Int. '||trim(v_address.interior_number) end,
      nullif(trim(coalesce(v_address.neighborhood,'')),''),
      case when nullif(trim(coalesce(v_address.postal_code,'')),'') is not null then 'CP '||trim(v_address.postal_code) end
    );
  else
    if not exists(select 1 from public.branches b where b.id=p_branch_id and b.active=true) then raise exception 'Sucursal inválida'; end if;
    v_branch_id:=p_branch_id;
    v_address_text:=null;
  end if;

  -- Calcula el subtotal en servidor. Un reward válido vale $0 y siempre es cantidad 1.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p where p.id=(v_item->>'product_id')::uuid and p.available=true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;
    if v_voucher_id is not null then
      select rv.* into v_voucher from public.reward_vouchers rv
        where rv.id=v_voucher_id and rv.user_id=v_user and rv.status='available';
      if not found then raise exception 'Este beneficio ya no está disponible'; end if;
      if v_voucher.reward_type<>'spring_rolls' or v_product.slug<>'spring-rolls' then
        raise exception 'El beneficio no corresponde a este producto';
      end if;
      if v_qty<>1 then raise exception 'Los rewards solo pueden agregarse una vez'; end if;
    else
      v_subtotal:=v_subtotal+(v_product.price*v_qty);
    end if;
  end loop;

  v_delivery_fee:=case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total:=v_subtotal+v_delivery_fee;

  insert into public.orders(user_id,branch_id,fulfillment_type,delivery_address,delivery_reference,delivery_notes,payment_method,status,subtotal,delivery_fee,total)
  values(v_user,v_branch_id,p_fulfillment_type,v_address_text,
    case when p_fulfillment_type='delivery' then v_address.notes else null end,
    p_delivery_notes,p_payment_method,'preparing',v_subtotal,v_delivery_fee,v_total)
  returning public.orders.id,public.orders.order_number into v_order_id,v_order_number;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));
    select p.* into v_product from public.products p where p.id=(v_item->>'product_id')::uuid;
    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is not null then
      -- Consumir el voucher aquí impide usar el mismo dos veces. Si algo falla, toda la transacción se revierte.
      update public.reward_vouchers rv
        set status='redeemed', redeemed_at=now()
        where rv.id=v_voucher_id and rv.user_id=v_user and rv.status='available' and rv.reward_type='spring_rolls';
      if not found then raise exception 'Este beneficio ya fue utilizado'; end if;
      insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
      values(v_order_id,v_product.id,v_product.name,0,1);
    else
      insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
      values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty);
    end if;
  end loop;

  return query select v_order_id,v_order_number,v_total;
end;
$$;

revoke all on function public.create_order(text,text,uuid,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,uuid,text,text,jsonb) to authenticated;


-- ===== v17 disponibilidad por sucursal =====
-- KYO v17 — Disponibilidad de productos y opciones por sucursal
-- Ejecutar UNA sola vez en Supabase SQL Editor.

create table if not exists public.product_branch_availability (
  product_id uuid not null references public.products(id) on delete cascade,
  branch_id text not null references public.branches(id) on delete cascade,
  available boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (product_id, branch_id)
);

create table if not exists public.customization_option_branch_availability (
  template_id uuid not null references public.customization_templates(id) on delete cascade,
  option_id text not null,
  branch_id text not null references public.branches(id) on delete cascade,
  available boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (template_id, option_id, branch_id)
);

alter table public.product_branch_availability enable row level security;
alter table public.customization_option_branch_availability enable row level security;

drop policy if exists "product branch availability public read" on public.product_branch_availability;
create policy "product branch availability public read"
on public.product_branch_availability for select
using (true);

drop policy if exists "admins manage product branch availability" on public.product_branch_availability;
create policy "admins manage product branch availability"
on public.product_branch_availability for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "option branch availability public read" on public.customization_option_branch_availability;
create policy "option branch availability public read"
on public.customization_option_branch_availability for select
using (true);

drop policy if exists "admins manage option branch availability" on public.customization_option_branch_availability;
create policy "admins manage option branch availability"
on public.customization_option_branch_availability for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Ausencia de registro significa "disponible".
-- Este trigger protege también el backend: aunque alguien altere React,
-- no puede pedir un producto u opción marcada como no disponible en la sucursal.
create or replace function public.validate_order_item_branch_availability()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_branch text;
  v_custom jsonb;
  v_template uuid;
  v_option text;
begin
  select o.branch_id into v_branch
  from public.orders o
  where o.id = new.order_id;

  if v_branch is null then
    raise exception 'No se pudo determinar la sucursal del pedido';
  end if;

  if exists (
    select 1
    from public.product_branch_availability pba
    where pba.product_id = new.product_id
      and pba.branch_id = v_branch
      and pba.available = false
  ) then
    raise exception 'Este producto no está disponible en la sucursal seleccionada';
  end if;

  for v_custom in
    select * from jsonb_array_elements(coalesce(new.customizations,'[]'::jsonb))
  loop
    v_template := nullif(v_custom->>'template_id','')::uuid;
    v_option := nullif(v_custom->>'option_id','');

    if v_template is not null and v_option is not null and exists (
      select 1
      from public.customization_option_branch_availability coba
      where coba.template_id = v_template
        and coba.option_id = v_option
        and coba.branch_id = v_branch
        and coba.available = false
    ) then
      raise exception 'Una opción seleccionada ya no está disponible en esta sucursal';
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists trg_validate_order_item_branch_availability on public.order_items;
create trigger trg_validate_order_item_branch_availability
before insert or update on public.order_items
for each row execute function public.validate_order_item_branch_availability();


-- ===== v18 rewards directo al carrito =====
-- KYO v18 — Rewards van directo al carrito.
-- Ejecutar UNA sola vez después de v17.
--
-- 250 puntos -> 4 Spring Rolls directo al carrito.
-- 6 pedidos -> cualquier rollo de subcategoría "Clásicos", con personalizaciones gratis.
-- Si el cliente quita un reward del carrito antes de ordenar, cancel_reward_voucher()
-- devuelve los 250 puntos o los 6 sellos.

create or replace function public.cancel_reward_voucher(p_voucher_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_voucher public.reward_vouchers%rowtype;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;

  select rv.* into v_voucher
  from public.reward_vouchers rv
  where rv.id=p_voucher_id
    and rv.user_id=v_user
    and rv.status='available'
  for update;

  if not found then
    return false;
  end if;

  if v_voucher.reward_type='spring_rolls' then
    update public.profiles
      set reward_points=reward_points+250
      where id=v_user;
  elsif v_voucher.reward_type='free_roll' then
    update public.profiles
      set reward_order_stamps=reward_order_stamps+6
      where id=v_user;
  else
    raise exception 'Tipo de reward inválido';
  end if;

  delete from public.reward_vouchers
  where id=v_voucher.id;

  return true;
end;
$$;

revoke all on function public.cancel_reward_voucher(uuid) from public;
grant execute on function public.cancel_reward_voucher(uuid) to authenticated;


create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_address_id uuid,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2):=0;
  v_delivery_fee numeric(10,2):=0;
  v_total numeric(10,2):=0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_address public.addresses%rowtype;
  v_branch_id text;
  v_address_text text;
  v_voucher_id uuid;
  v_voucher public.reward_vouchers%rowtype;
  v_custom jsonb;
  v_template public.customization_templates%rowtype;
  v_option jsonb;
  v_option_price numeric(10,2);
  v_custom_qty integer;
  v_item_extra numeric(10,2);
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'El carrito está vacío'; end if;

  if p_fulfillment_type='delivery' then
    if p_address_id is null then raise exception 'Falta dirección de entrega'; end if;
    select a.* into v_address
    from public.addresses a
    where a.id=p_address_id and a.user_id=v_user;
    if not found then raise exception 'Dirección inválida'; end if;

    v_branch_id:=v_address.branch_id;
    v_address_text:=concat_ws(', ',
      nullif(trim(coalesce(v_address.street,v_address.address_line)),''),
      case when nullif(trim(coalesce(v_address.exterior_number,'')),'') is not null then '#'||trim(v_address.exterior_number) end,
      case when nullif(trim(coalesce(v_address.interior_number,'')),'') is not null then 'Int. '||trim(v_address.interior_number) end,
      nullif(trim(coalesce(v_address.neighborhood,'')),''),
      case when nullif(trim(coalesce(v_address.postal_code,'')),'') is not null then 'CP '||trim(v_address.postal_code) end
    );
  else
    if not exists(select 1 from public.branches b where b.id=p_branch_id and b.active=true) then
      raise exception 'Sucursal inválida';
    end if;
    v_branch_id:=p_branch_id;
    v_address_text:=null;
  end if;

  -- Primera pasada: validar y calcular subtotal completamente en servidor.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid and p.available=true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;

    if exists(
      select 1 from public.product_branch_availability pba
      where pba.product_id=v_product.id
        and pba.branch_id=v_branch_id
        and pba.available=false
    ) then
      raise exception '% no está disponible en esta sucursal',v_product.name;
    end if;

    v_item_extra:=0;

    for v_custom in
      select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb))
    loop
      select ct.* into v_template
      from public.customization_templates ct
      join public.product_customizations pc on pc.template_id=ct.id
      where pc.product_id=v_product.id
        and ct.id=(v_custom->>'template_id')::uuid;

      if not found then
        raise exception 'Personalización inválida para %',v_product.name;
      end if;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      if v_option is null then
        raise exception 'Opción de personalización inválida';
      end if;

      if exists(
        select 1
        from public.customization_option_branch_availability coba
        where coba.template_id=v_template.id
          and coba.option_id=v_custom->>'option_id'
          and coba.branch_id=v_branch_id
          and coba.available=false
      ) then
        raise exception 'Una personalización seleccionada no está disponible en esta sucursal';
      end if;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_option_price:=coalesce((v_option->>'price')::numeric,0);
      v_item_extra:=v_item_extra+(v_option_price*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      v_subtotal:=v_subtotal+((v_product.price+v_item_extra)*v_qty);
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available';

      if not found then raise exception 'Este reward ya no está disponible'; end if;
      if v_qty<>1 then raise exception 'Los rewards solo pueden agregarse una vez'; end if;

      if v_voucher.reward_type='spring_rolls' then
        if v_product.slug<>'spring-rolls' then
          raise exception 'Este reward corresponde únicamente a 4 Spring Rolls';
        end if;
        -- Spring Rolls gratis; personalizaciones con costo sí se cobran.
        v_subtotal:=v_subtotal+v_item_extra;

      elsif v_voucher.reward_type='free_roll' then
        if not exists(
          select 1
          from public.categories c
          where c.id=v_product.subcategory_id
            and (
              lower(c.name) in ('clásicos','clasicos')
              or lower(c.slug) in ('clasicos','clásicos')
            )
        ) then
          raise exception 'El reward de 6 pedidos solo aplica a rollos Clásicos';
        end if;
        -- Rollo + todas sus personalizaciones = $0.
        v_subtotal:=v_subtotal+0;

      else
        raise exception 'Tipo de reward inválido';
      end if;
    end if;
  end loop;

  v_delivery_fee:=case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total:=v_subtotal+v_delivery_fee;

  insert into public.orders(
    user_id,branch_id,fulfillment_type,delivery_address,delivery_reference,
    delivery_notes,payment_method,status,subtotal,delivery_fee,total
  )
  values(
    v_user,v_branch_id,p_fulfillment_type,v_address_text,
    case when p_fulfillment_type='delivery' then v_address.notes else null end,
    p_delivery_notes,p_payment_method,'preparing',v_subtotal,v_delivery_fee,v_total
  )
  returning public.orders.id,public.orders.order_number
  into v_order_id,v_order_number;

  -- Segunda pasada: guardar líneas y consumir rewards.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid;

    v_item_extra:=0;
    for v_custom in
      select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb))
    loop
      select ct.* into v_template
      from public.customization_templates ct
      where ct.id=(v_custom->>'template_id')::uuid;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_item_extra:=v_item_extra+(coalesce((v_option->>'price')::numeric,0)*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,
        v_product.price+v_item_extra,v_qty,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available'
      for update;

      if not found then raise exception 'Este reward ya fue utilizado'; end if;

      update public.reward_vouchers rv
      set status='redeemed',redeemed_at=now()
      where rv.id=v_voucher.id;

      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,
        case when v_voucher.reward_type='spring_rolls' then v_item_extra else 0 end,
        1,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    end if;
  end loop;

  return query select v_order_id,v_order_number,v_total;
end;
$$;

revoke all on function public.create_order(text,text,uuid,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,uuid,text,text,jsonb) to authenticated;


-- ===== v20 pickup + mínimo + reward configurable =====
-- KYO v20 — Pickup tracking + pedido mínimo + reward configurable
-- Ejecutar UNA sola vez en Supabase SQL Editor sobre la base actual.

-- =========================================================
-- 1) CONFIGURACIÓN GLOBAL DEL NEGOCIO
-- =========================================================
create table if not exists public.app_settings (
  id text primary key default 'main',
  minimum_order numeric(10,2) not null default 200 check (minimum_order >= 0),
  points_reward_cost integer not null default 250 check (points_reward_cost > 0),
  points_reward_product_id uuid references public.products(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings(id,minimum_order,points_reward_cost,points_reward_product_id)
values(
  'main',
  200,
  250,
  (select p.id from public.products p where p.slug='spring-rolls' or lower(p.name)='4 spring rolls' limit 1)
)
on conflict (id) do nothing;

alter table public.app_settings enable row level security;

drop policy if exists "app settings public read" on public.app_settings;
create policy "app settings public read"
on public.app_settings for select
using (true);

drop policy if exists "admins manage app settings" on public.app_settings;
create policy "admins manage app settings"
on public.app_settings for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

grant select on public.app_settings to anon, authenticated;
grant insert, update, delete on public.app_settings to authenticated;

-- =========================================================
-- 2) GUARDAR QUÉ PRODUCTO/COSTO PERTENECÍA AL VOUCHER
--    Así si KYO cambia la configuración después, el voucher
--    que ya estaba en carrito sigue siendo válido y se
--    devuelven exactamente los puntos gastados al quitarlo.
-- =========================================================
alter table public.reward_vouchers
  add column if not exists reward_product_id uuid references public.products(id) on delete set null;

alter table public.reward_vouchers
  add column if not exists points_spent integer;

-- Compatibilidad con rewards de puntos que ya estuvieran reservados antes de v20.
update public.reward_vouchers rv
set reward_product_id=coalesce(rv.reward_product_id,s.points_reward_product_id),
    points_spent=coalesce(rv.points_spent,250)
from public.app_settings s
where s.id='main'
  and rv.reward_type='spring_rolls'
  and rv.status='available';

-- =========================================================
-- 3) REWARD DE PUNTOS DINÁMICO
-- =========================================================
create or replace function public.redeem_spring_rolls_reward()
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_id uuid;
  v_cost integer;
  v_product_id uuid;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;

  select s.points_reward_cost,s.points_reward_product_id
    into v_cost,v_product_id
  from public.app_settings s
  where s.id='main';

  if v_product_id is null then
    raise exception 'KYO todavía no ha configurado el producto del reward por puntos';
  end if;

  if not exists(select 1 from public.products p where p.id=v_product_id and p.available=true) then
    raise exception 'El producto configurado para este reward no está disponible';
  end if;

  update public.profiles
  set reward_points=reward_points-v_cost
  where id=v_user and reward_points>=v_cost;

  if not found then
    raise exception 'No tienes suficientes puntos disponibles';
  end if;

  insert into public.reward_vouchers(
    user_id,reward_type,reward_product_id,points_spent
  )
  values(
    v_user,'spring_rolls',v_product_id,v_cost
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.redeem_spring_rolls_reward() from public;
grant execute on function public.redeem_spring_rolls_reward() to authenticated;

-- =========================================================
-- 4) AL QUITAR REWARD DEL CARRITO, DEVOLVER LO QUE GASTÓ
-- =========================================================
create or replace function public.cancel_reward_voucher(p_voucher_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_voucher public.reward_vouchers%rowtype;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;

  select rv.* into v_voucher
  from public.reward_vouchers rv
  where rv.id=p_voucher_id
    and rv.user_id=v_user
    and rv.status='available'
  for update;

  if not found then
    return false;
  end if;

  if v_voucher.reward_type='spring_rolls' then
    update public.profiles
      set reward_points=reward_points+coalesce(v_voucher.points_spent,250)
      where id=v_user;
  elsif v_voucher.reward_type='free_roll' then
    update public.profiles
      set reward_order_stamps=reward_order_stamps+6
      where id=v_user;
  else
    raise exception 'Tipo de reward inválido';
  end if;

  delete from public.reward_vouchers where id=v_voucher.id;
  return true;
end;
$$;

revoke all on function public.cancel_reward_voucher(uuid) from public;
grant execute on function public.cancel_reward_voucher(uuid) to authenticated;

-- =========================================================
-- 5) CREATE_ORDER:
--    - pedido mínimo configurable
--    - reward por puntos valida el producto configurado
--    - mantiene reward de 6 pedidos / Clásicos
--    - mantiene disponibilidad por sucursal
-- =========================================================
create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_address_id uuid,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2):=0;
  v_delivery_fee numeric(10,2):=0;
  v_total numeric(10,2):=0;
  v_minimum_order numeric(10,2):=200;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_address public.addresses%rowtype;
  v_branch_id text;
  v_address_text text;
  v_voucher_id uuid;
  v_voucher public.reward_vouchers%rowtype;
  v_custom jsonb;
  v_template public.customization_templates%rowtype;
  v_option jsonb;
  v_option_price numeric(10,2);
  v_custom_qty integer;
  v_item_extra numeric(10,2);
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'El carrito está vacío'; end if;

  select coalesce(s.minimum_order,200)
  into v_minimum_order
  from public.app_settings s
  where s.id='main';

  v_minimum_order:=coalesce(v_minimum_order,200);

  if p_fulfillment_type='delivery' then
    if p_address_id is null then raise exception 'Falta dirección de entrega'; end if;
    select a.* into v_address
    from public.addresses a
    where a.id=p_address_id and a.user_id=v_user;
    if not found then raise exception 'Dirección inválida'; end if;

    v_branch_id:=v_address.branch_id;
    v_address_text:=concat_ws(', ',
      nullif(trim(coalesce(v_address.street,v_address.address_line)),''),
      case when nullif(trim(coalesce(v_address.exterior_number,'')),'') is not null then '#'||trim(v_address.exterior_number) end,
      case when nullif(trim(coalesce(v_address.interior_number,'')),'') is not null then 'Int. '||trim(v_address.interior_number) end,
      nullif(trim(coalesce(v_address.neighborhood,'')),''),
      case when nullif(trim(coalesce(v_address.postal_code,'')),'') is not null then 'CP '||trim(v_address.postal_code) end
    );
  else
    if not exists(select 1 from public.branches b where b.id=p_branch_id and b.active=true) then
      raise exception 'Sucursal inválida';
    end if;
    v_branch_id:=p_branch_id;
    v_address_text:=null;
  end if;

  -- Primera pasada: validar y calcular subtotal real.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid and p.available=true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;

    if exists(
      select 1 from public.product_branch_availability pba
      where pba.product_id=v_product.id
        and pba.branch_id=v_branch_id
        and pba.available=false
    ) then
      raise exception '% no está disponible en esta sucursal',v_product.name;
    end if;

    v_item_extra:=0;

    for v_custom in
      select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb))
    loop
      select ct.* into v_template
      from public.customization_templates ct
      join public.product_customizations pc on pc.template_id=ct.id
      where pc.product_id=v_product.id
        and ct.id=(v_custom->>'template_id')::uuid;

      if not found then raise exception 'Personalización inválida para %',v_product.name; end if;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      if v_option is null then raise exception 'Opción de personalización inválida'; end if;

      if exists(
        select 1
        from public.customization_option_branch_availability coba
        where coba.template_id=v_template.id
          and coba.option_id=v_custom->>'option_id'
          and coba.branch_id=v_branch_id
          and coba.available=false
      ) then
        raise exception 'Una personalización seleccionada no está disponible en esta sucursal';
      end if;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_option_price:=coalesce((v_option->>'price')::numeric,0);
      v_item_extra:=v_item_extra+(v_option_price*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      v_subtotal:=v_subtotal+((v_product.price+v_item_extra)*v_qty);
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available';

      if not found then raise exception 'Este reward ya no está disponible'; end if;
      if v_qty<>1 then raise exception 'Los rewards solo pueden agregarse una vez'; end if;

      if v_voucher.reward_type='spring_rolls' then
        if v_voucher.reward_product_id is null or v_product.id<>v_voucher.reward_product_id then
          raise exception 'Este reward no corresponde al producto seleccionado';
        end if;
        -- Producto gratis. Los extras de personalización, si los hay, conservan su costo.
        v_subtotal:=v_subtotal+v_item_extra;

      elsif v_voucher.reward_type='free_roll' then
        if not exists(
          select 1
          from public.categories c
          where c.id=v_product.subcategory_id
            and (
              lower(c.name) in ('clásicos','clasicos')
              or lower(c.slug) in ('clasicos','clásicos')
            )
        ) then
          raise exception 'El reward de 6 pedidos solo aplica a rollos Clásicos';
        end if;
        -- Rollo + sus personalizaciones gratis.
        v_subtotal:=v_subtotal+0;
      else
        raise exception 'Tipo de reward inválido';
      end if;
    end if;
  end loop;

  if v_subtotal < v_minimum_order then
    raise exception 'El pedido mínimo es de $%. Te faltan $% en productos',
      trim(to_char(v_minimum_order,'FM999999990.00')),
      trim(to_char(v_minimum_order-v_subtotal,'FM999999990.00'));
  end if;

  v_delivery_fee:=case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total:=v_subtotal+v_delivery_fee;

  insert into public.orders(
    user_id,branch_id,fulfillment_type,delivery_address,delivery_reference,
    delivery_notes,payment_method,status,subtotal,delivery_fee,total
  )
  values(
    v_user,v_branch_id,p_fulfillment_type,v_address_text,
    case when p_fulfillment_type='delivery' then v_address.notes else null end,
    p_delivery_notes,p_payment_method,'preparing',v_subtotal,v_delivery_fee,v_total
  )
  returning public.orders.id,public.orders.order_number
  into v_order_id,v_order_number;

  -- Segunda pasada: guardar líneas y consumir vouchers.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid;

    v_item_extra:=0;
    for v_custom in select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb)) loop
      select ct.* into v_template
      from public.customization_templates ct
      where ct.id=(v_custom->>'template_id')::uuid;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_item_extra:=v_item_extra+(coalesce((v_option->>'price')::numeric,0)*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,v_product.price+v_item_extra,v_qty,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available'
      for update;

      if not found then raise exception 'Este reward ya fue utilizado'; end if;

      update public.reward_vouchers rv
      set status='redeemed',redeemed_at=now()
      where rv.id=v_voucher.id;

      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,
        case when v_voucher.reward_type='spring_rolls' then v_item_extra else 0 end,
        1,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    end if;
  end loop;

  return query select v_order_id,v_order_number,v_total;
end;
$$;

revoke all on function public.create_order(text,text,uuid,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,uuid,text,text,jsonb) to authenticated;


-- ===== v22.5 points =====
-- KYO v22.5
-- Rewards: 1 punto por cada $10 de subtotal entregado.
-- Panel: administradores pueden agregar puntos a una cuenta por correo.

create or replace function public.award_rewards_on_delivery()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.status='delivered'
     and old.status is distinct from 'delivered'
     and new.rewards_awarded=false then

    if new.user_id is not null then
      update public.profiles
      set reward_points=reward_points+floor(new.subtotal/10)::int,
          reward_order_stamps=reward_order_stamps+1,
          updated_at=now()
      where id=new.user_id;
    end if;

    new.rewards_awarded:=true;
  end if;

  new.updated_at:=now();
  return new;
end;
$$;

drop trigger if exists orders_award_rewards on public.orders;
create trigger orders_award_rewards
before update on public.orders
for each row execute procedure public.award_rewards_on_delivery();


create or replace function public.admin_add_reward_points(
  p_email text,
  p_points integer
)
returns table(
  user_id uuid,
  email text,
  full_name text,
  reward_points integer
)
language plpgsql
security definer
set search_path=public,auth
as $$
declare
  v_user_id uuid;
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception 'No tienes permisos de administrador';
  end if;

  if coalesce(trim(p_email),'')='' then
    raise exception 'Escribe el correo del usuario';
  end if;

  if coalesce(p_points,0)<=0 then
    raise exception 'Los puntos deben ser mayores a 0';
  end if;

  select u.id
    into v_user_id
  from auth.users u
  where lower(u.email)=lower(trim(p_email))
  limit 1;

  if v_user_id is null then
    raise exception 'No encontramos una cuenta con ese correo';
  end if;

  update public.profiles p
  set reward_points=p.reward_points+p_points,
      updated_at=now()
  where p.id=v_user_id;

  if not found then
    raise exception 'La cuenta no tiene un perfil KYO';
  end if;

  return query
  select p.id,u.email,p.full_name,p.reward_points
  from public.profiles p
  join auth.users u on u.id=p.id
  where p.id=v_user_id;
end;
$$;

revoke all on function public.admin_add_reward_points(text,integer) from public;
grant execute on function public.admin_add_reward_points(text,integer) to authenticated;


-- ===== v22.6 business hours =====
-- KYO v22.6 — Horarios configurables usando SIEMPRE hora de Ciudad de México.
-- Ejecutar UNA sola vez.

alter table public.app_settings
add column if not exists business_hours jsonb not null default
'{
  "mon":{"closed":true,"open":"13:00","close":"21:00"},
  "tue":{"closed":false,"open":"13:00","close":"21:00"},
  "wed":{"closed":false,"open":"13:00","close":"21:00"},
  "thu":{"closed":false,"open":"13:00","close":"22:00"},
  "fri":{"closed":false,"open":"13:00","close":"22:00"},
  "sat":{"closed":false,"open":"13:00","close":"22:00"},
  "sun":{"closed":false,"open":"13:00","close":"22:00"}
}'::jsonb;

update public.app_settings
set business_hours =
'{
  "mon":{"closed":true,"open":"13:00","close":"21:00"},
  "tue":{"closed":false,"open":"13:00","close":"21:00"},
  "wed":{"closed":false,"open":"13:00","close":"21:00"},
  "thu":{"closed":false,"open":"13:00","close":"22:00"},
  "fri":{"closed":false,"open":"13:00","close":"22:00"},
  "sat":{"closed":false,"open":"13:00","close":"22:00"},
  "sun":{"closed":false,"open":"13:00","close":"22:00"}
}'::jsonb
where id='main'
  and (business_hours is null or business_hours='{}'::jsonb);


create or replace function public.is_store_open_now()
returns boolean
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_local timestamp;
  v_day_key text;
  v_day jsonb;
  v_open time;
  v_close time;
begin
  -- No depende de la zona horaria del cliente.
  v_local := timezone('America/Mexico_City', now());

  v_day_key := case extract(isodow from v_local)::int
    when 1 then 'mon'
    when 2 then 'tue'
    when 3 then 'wed'
    when 4 then 'thu'
    when 5 then 'fri'
    when 6 then 'sat'
    when 7 then 'sun'
  end;

  select s.business_hours->v_day_key
    into v_day
  from public.app_settings s
  where s.id='main';

  if v_day is null then
    return false;
  end if;

  if coalesce((v_day->>'closed')::boolean,false) then
    return false;
  end if;

  v_open := (v_day->>'open')::time;
  v_close := (v_day->>'close')::time;

  return v_local::time >= v_open
     and v_local::time < v_close;
end;
$$;

revoke all on function public.is_store_open_now() from public;
grant execute on function public.is_store_open_now() to anon, authenticated;


create or replace function public.prevent_orders_outside_business_hours()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_store_open_now() then
    raise exception 'KYO está cerrado en este momento. Intenta nuevamente dentro de nuestro horario de servicio.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_orders_business_hours on public.orders;
create trigger trg_orders_business_hours
before insert on public.orders
for each row execute function public.prevent_orders_outside_business_hours();


-- ===== v22.8 production errors + account deletion =====
-- KYO v22.8 — eliminación de cuenta de producción
-- Ejecutar UNA sola vez en la base actual.
--
-- Objetivos:
-- 1) No permitir borrar una cuenta con pedidos activos.
-- 2) Conservar pedidos históricos del restaurante sin ligarlos al usuario.
-- 3) Eliminar/anular datos personales de entrega del historial.
-- 4) Borrar perfil, direcciones, rewards y autenticación del cliente.

alter table public.orders
  alter column user_id drop not null;

alter table public.orders
  drop constraint if exists orders_user_id_fkey;

alter table public.orders
  add constraint orders_user_id_fkey
  foreign key (user_id)
  references public.profiles(id)
  on delete set null;


create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path=public,auth
as $$
declare
  v_user uuid:=auth.uid();
begin
  if v_user is null then
    raise exception 'Debes iniciar sesión';
  end if;

  -- No borrar mientras Cocina/Reparto todavía necesiten identificar al cliente.
  if exists(
    select 1
    from public.orders o
    where o.user_id=v_user
      and o.status in ('received','accepted','preparing','ready','on_the_way')
  ) then
    raise exception 'No puedes eliminar tu cuenta mientras tengas un pedido activo. Espera a que termine o contacta a KYO.';
  end if;

  -- El restaurante conserva importes, productos, fecha, sucursal y número de pedido,
  -- pero se quitan datos personales de entrega del historial.
  update public.orders
  set delivery_address=null,
      delivery_reference=null,
      delivery_notes=null,
      updated_at=now()
  where user_id=v_user;

  -- Estas tablas también se eliminarían por cascada al borrar auth.users/profile,
  -- pero se hace explícito para que la intención de privacidad sea clara.
  delete from public.reward_vouchers where user_id=v_user;
  delete from public.addresses where user_id=v_user;

  -- El perfil se elimina por cascade desde auth.users.
  -- El FK de orders pasa user_id a NULL y conserva el registro histórico.
  delete from auth.users where id=v_user;
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;


-- ===== v22.9 order idempotency =====
-- KYO v22.9 — protección real contra pedidos duplicados.
-- Ejecutar UNA sola vez en Supabase SQL Editor.

alter table public.orders
  add column if not exists client_request_id uuid;

create unique index if not exists orders_user_client_request_uidx
  on public.orders(user_id,client_request_id)
  where client_request_id is not null;

-- Bloquear la firma anterior para clientes autenticados: los pedidos nuevos deben traer idempotency key.
revoke execute on function public.create_order(text,text,uuid,text,text,jsonb) from authenticated;

create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_address_id uuid,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb,
  p_idempotency_key uuid
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2):=0;
  v_delivery_fee numeric(10,2):=0;
  v_total numeric(10,2):=0;
  v_minimum_order numeric(10,2):=200;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_address public.addresses%rowtype;
  v_branch_id text;
  v_address_text text;
  v_voucher_id uuid;
  v_voucher public.reward_vouchers%rowtype;
  v_custom jsonb;
  v_template public.customization_templates%rowtype;
  v_option jsonb;
  v_option_price numeric(10,2);
  v_custom_qty integer;
  v_item_extra numeric(10,2);
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_idempotency_key is null then raise exception 'Falta identificador de seguridad del pedido'; end if;

  -- Si esta misma solicitud ya creó el pedido, regresar exactamente ese pedido.
  select o.id,o.order_number,o.total
    into v_order_id,v_order_number,v_total
  from public.orders o
  where o.user_id=v_user
    and o.client_request_id=p_idempotency_key
  limit 1;

  if found then
    return query select v_order_id,v_order_number,v_total;
    return;
  end if;

  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'El carrito está vacío'; end if;

  select coalesce(s.minimum_order,200)
  into v_minimum_order
  from public.app_settings s
  where s.id='main';

  v_minimum_order:=coalesce(v_minimum_order,200);

  if p_fulfillment_type='delivery' then
    if p_address_id is null then raise exception 'Falta dirección de entrega'; end if;
    select a.* into v_address
    from public.addresses a
    where a.id=p_address_id and a.user_id=v_user;
    if not found then raise exception 'Dirección inválida'; end if;

    v_branch_id:=v_address.branch_id;
    v_address_text:=concat_ws(', ',
      nullif(trim(coalesce(v_address.street,v_address.address_line)),''),
      case when nullif(trim(coalesce(v_address.exterior_number,'')),'') is not null then '#'||trim(v_address.exterior_number) end,
      case when nullif(trim(coalesce(v_address.interior_number,'')),'') is not null then 'Int. '||trim(v_address.interior_number) end,
      nullif(trim(coalesce(v_address.neighborhood,'')),''),
      case when nullif(trim(coalesce(v_address.postal_code,'')),'') is not null then 'CP '||trim(v_address.postal_code) end
    );
  else
    if not exists(select 1 from public.branches b where b.id=p_branch_id and b.active=true) then
      raise exception 'Sucursal inválida';
    end if;
    v_branch_id:=p_branch_id;
    v_address_text:=null;
  end if;

  -- Primera pasada: validar y calcular subtotal real.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid and p.available=true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;

    if exists(
      select 1 from public.product_branch_availability pba
      where pba.product_id=v_product.id
        and pba.branch_id=v_branch_id
        and pba.available=false
    ) then
      raise exception '% no está disponible en esta sucursal',v_product.name;
    end if;

    v_item_extra:=0;

    for v_custom in
      select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb))
    loop
      select ct.* into v_template
      from public.customization_templates ct
      join public.product_customizations pc on pc.template_id=ct.id
      where pc.product_id=v_product.id
        and ct.id=(v_custom->>'template_id')::uuid;

      if not found then raise exception 'Personalización inválida para %',v_product.name; end if;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      if v_option is null then raise exception 'Opción de personalización inválida'; end if;

      if exists(
        select 1
        from public.customization_option_branch_availability coba
        where coba.template_id=v_template.id
          and coba.option_id=v_custom->>'option_id'
          and coba.branch_id=v_branch_id
          and coba.available=false
      ) then
        raise exception 'Una personalización seleccionada no está disponible en esta sucursal';
      end if;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_option_price:=coalesce((v_option->>'price')::numeric,0);
      v_item_extra:=v_item_extra+(v_option_price*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      v_subtotal:=v_subtotal+((v_product.price+v_item_extra)*v_qty);
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available';

      if not found then raise exception 'Este reward ya no está disponible'; end if;
      if v_qty<>1 then raise exception 'Los rewards solo pueden agregarse una vez'; end if;

      if v_voucher.reward_type='spring_rolls' then
        if v_voucher.reward_product_id is null or v_product.id<>v_voucher.reward_product_id then
          raise exception 'Este reward no corresponde al producto seleccionado';
        end if;
        -- Producto gratis. Los extras de personalización, si los hay, conservan su costo.
        v_subtotal:=v_subtotal+v_item_extra;

      elsif v_voucher.reward_type='free_roll' then
        if not exists(
          select 1
          from public.categories c
          where c.id=v_product.subcategory_id
            and (
              lower(c.name) in ('clásicos','clasicos')
              or lower(c.slug) in ('clasicos','clásicos')
            )
        ) then
          raise exception 'El reward de 6 pedidos solo aplica a rollos Clásicos';
        end if;
        -- Rollo + sus personalizaciones gratis.
        v_subtotal:=v_subtotal+0;
      else
        raise exception 'Tipo de reward inválido';
      end if;
    end if;
  end loop;

  if v_subtotal < v_minimum_order then
    raise exception 'El pedido mínimo es de $%. Te faltan $% en productos',
      trim(to_char(v_minimum_order,'FM999999990.00')),
      trim(to_char(v_minimum_order-v_subtotal,'FM999999990.00'));
  end if;

  v_delivery_fee:=case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total:=v_subtotal+v_delivery_fee;

  insert into public.orders(
    user_id,client_request_id,branch_id,fulfillment_type,delivery_address,delivery_reference,
    delivery_notes,payment_method,status,subtotal,delivery_fee,total
  )
  values(
    v_user,p_idempotency_key,v_branch_id,p_fulfillment_type,v_address_text,
    case when p_fulfillment_type='delivery' then v_address.notes else null end,
    p_delivery_notes,p_payment_method,'preparing',v_subtotal,v_delivery_fee,v_total
  )
  returning public.orders.id,public.orders.order_number
  into v_order_id,v_order_number;

  -- Segunda pasada: guardar líneas y consumir vouchers.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(20,coalesce((v_item->>'quantity')::int,1)));

    select p.* into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::uuid;

    v_item_extra:=0;
    for v_custom in select * from jsonb_array_elements(coalesce(v_item->'customizations','[]'::jsonb)) loop
      select ct.* into v_template
      from public.customization_templates ct
      where ct.id=(v_custom->>'template_id')::uuid;

      select o into v_option
      from jsonb_array_elements(v_template.options) o
      where o->>'id'=v_custom->>'option_id'
      limit 1;

      v_custom_qty:=greatest(1,least(20,coalesce((v_custom->>'quantity')::int,1)));
      v_item_extra:=v_item_extra+(coalesce((v_option->>'price')::numeric,0)*v_custom_qty);
    end loop;

    v_voucher_id:=nullif(v_item->>'reward_voucher_id','')::uuid;

    if v_voucher_id is null then
      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,v_product.price+v_item_extra,v_qty,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    else
      select rv.* into v_voucher
      from public.reward_vouchers rv
      where rv.id=v_voucher_id
        and rv.user_id=v_user
        and rv.status='available'
      for update;

      if not found then raise exception 'Este reward ya fue utilizado'; end if;

      update public.reward_vouchers rv
      set status='redeemed',redeemed_at=now()
      where rv.id=v_voucher.id;

      insert into public.order_items(
        order_id,product_id,product_name,unit_price,quantity,customizations,item_note
      )
      values(
        v_order_id,v_product.id,v_product.name,
        case when v_voucher.reward_type='spring_rolls' then v_item_extra else 0 end,
        1,
        coalesce(v_item->'customizations','[]'::jsonb),
        left(coalesce(v_item->>'item_note',''),250)
      );
    end if;
  end loop;

  return query select v_order_id,v_order_number,v_total;
  return;

exception
  when unique_violation then
    -- Dos requests idénticos pudieron llegar al mismo tiempo.
    -- El índice único garantiza que solo uno se crea; el segundo recibe el mismo pedido.
    select o.id,o.order_number,o.total
      into v_order_id,v_order_number,v_total
    from public.orders o
    where o.user_id=v_user
      and o.client_request_id=p_idempotency_key
    limit 1;

    if found then
      return query select v_order_id,v_order_number,v_total;
      return;
    end if;

    raise;
end;
$$;

revoke all on function public.create_order(text,text,uuid,text,text,jsonb,uuid) from public;
grant execute on function public.create_order(text,text,uuid,text,text,jsonb,uuid) to authenticated;
