-- KYO Sushi - esquema inicial Supabase
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  is_admin boolean not null default false,
  reward_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id text primary key,
  name text not null,
  short_name text not null,
  address text not null,
  phone text,
  eta text,
  active boolean not null default true
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  category_id uuid references public.categories(id) on delete set null,
  image_url text,
  featured boolean not null default false,
  spicy boolean not null default false,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Dirección',
  address_line text not null,
  notes text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid not null references public.profiles(id) on delete restrict,
  branch_id text not null references public.branches(id),
  fulfillment_type text not null check (fulfillment_type in ('delivery','pickup')),
  delivery_address text,
  delivery_notes text,
  payment_method text not null default 'cash',
  status text not null default 'received' check (status in ('received','accepted','preparing','ready','on_the_way','delivered','cancelled')),
  subtotal numeric(10,2) not null,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  rewards_awarded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity > 0)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles p where p.id = uid and p.is_admin = true);
$$;

create or replace function public.create_order(
  p_branch_id text,
  p_fulfillment_type text,
  p_delivery_address text,
  p_delivery_notes text,
  p_payment_method text,
  p_items jsonb
)
returns table(id uuid, order_number bigint, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal numeric(10,2) := 0;
  v_delivery_fee numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
begin
  if v_user is null then raise exception 'Debes iniciar sesión'; end if;
  if p_fulfillment_type not in ('delivery','pickup') then raise exception 'Tipo de entrega inválido'; end if;
  if p_fulfillment_type = 'delivery' and coalesce(trim(p_delivery_address),'') = '' then raise exception 'Falta dirección de entrega'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb)) = 0 then raise exception 'El carrito está vacío'; end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select * into v_product from public.products
      where id = (v_item->>'product_id')::uuid and available = true;
    if not found then raise exception 'Uno de los productos ya no está disponible'; end if;
    v_subtotal := v_subtotal + (v_product.price * v_qty);
  end loop;

  v_delivery_fee := case when p_fulfillment_type='delivery' then 39 else 0 end;
  v_total := v_subtotal + v_delivery_fee;

  insert into public.orders(user_id,branch_id,fulfillment_type,delivery_address,delivery_notes,payment_method,subtotal,delivery_fee,total)
  values(v_user,p_branch_id,p_fulfillment_type,p_delivery_address,p_delivery_notes,p_payment_method,v_subtotal,v_delivery_fee,v_total)
  returning public.orders.id, public.orders.order_number into v_order_id, v_order_number;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, least(20, coalesce((v_item->>'quantity')::int,1)));
    select * into v_product from public.products where id = (v_item->>'product_id')::uuid;
    insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
    values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty);
  end loop;

  return query select v_order_id, v_order_number, v_total;
end;
$$;

revoke all on function public.create_order(text,text,text,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,text,text,text,jsonb) to authenticated;

create or replace function public.award_rewards_on_delivery()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.status = 'delivered' and old.status is distinct from 'delivered' and new.rewards_awarded = false then
    update public.profiles
      set reward_points = reward_points + floor(new.subtotal)::int,
          updated_at = now()
      where id = new.user_id;
    new.rewards_awarded := true;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists orders_award_rewards on public.orders;
create trigger orders_award_rewards
before update on public.orders
for each row execute procedure public.award_rewards_on_delivery();

alter table public.profiles enable row level security;
alter table public.branches enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Lectura pública del catálogo
create policy "branches public read" on public.branches for select using (active = true or public.is_admin(auth.uid()));
create policy "categories public read" on public.categories for select using (active = true or public.is_admin(auth.uid()));
create policy "products public read" on public.products for select using (available = true or public.is_admin(auth.uid()));

-- Perfil
create policy "profile own read" on public.profiles for select using (auth.uid() = id or public.is_admin(auth.uid()));
create policy "profile own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and is_admin = false);
create policy "admins manage profiles" on public.profiles for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Direcciones
create policy "addresses own select" on public.addresses for select using (auth.uid() = user_id or public.is_admin(auth.uid()));
create policy "addresses own insert" on public.addresses for insert with check (auth.uid() = user_id);
create policy "addresses own update" on public.addresses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "addresses own delete" on public.addresses for delete using (auth.uid() = user_id);

-- Pedidos
create policy "orders own select" on public.orders for select using (auth.uid() = user_id or public.is_admin(auth.uid()));
create policy "admins update orders" on public.orders for update using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "order items own select" on public.order_items for select using (
  exists(select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin(auth.uid())))
);

-- Admin catálogo
create policy "admins manage branches" on public.branches for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins manage categories" on public.categories for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admins manage products" on public.products for all using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Storage público para fotos del menú
insert into storage.buckets (id, name, public)
values ('menu-images','menu-images',true)
on conflict (id) do update set public = true;

create policy "menu images public read" on storage.objects for select using (bucket_id = 'menu-images');
create policy "admins upload menu images" on storage.objects for insert with check (bucket_id = 'menu-images' and public.is_admin(auth.uid()));
create policy "admins update menu images" on storage.objects for update using (bucket_id = 'menu-images' and public.is_admin(auth.uid()));
create policy "admins delete menu images" on storage.objects for delete using (bucket_id = 'menu-images' and public.is_admin(auth.uid()));


-- Habilita cambios de pedidos en Realtime para el panel.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- Sucursales
insert into public.branches (id,name,short_name,address,phone,eta) values
('zakia','KYO Zákia','Zákia','Plaza UNITY, local 103 PB, Zákia.','442 890 3797','35–50 min'),
('milenio','KYO Milenio','Milenio','Plaza UBIKA Milenio, local 112, Milenio III.','442 283 4928','35–50 min')
on conflict (id) do update set name=excluded.name, short_name=excluded.short_name, address=excluded.address, phone=excluded.phone, eta=excluded.eta;

insert into public.categories(name,slug,sort_order) values
('Entradas','entradas',10),('Kushiagues','kushiagues',20),('Sopas','sopas',30),('Ramen','ramen',40),('Poke Bowl','poke-bowl',50),('Rollos','rollos',60),('Arroz','arroz',70),('Postres','postres',80)
on conflict (slug) do update set name=excluded.name, sort_order=excluded.sort_order;

-- 20 productos demo del menú KYO 2026. Las imágenes locales se sirven desde Vercel;
-- cuando el admin suba una nueva foto, image_url se reemplaza por la URL de Supabase Storage.
with seed(slug,name,cat,price,description,image_url,featured,spicy,sort_order) as (values
('edamames','Edamames','entradas',98,'150 g · Al vapor, asados con mantequilla y soya o spicy lemon.','/assets/menu/edamames.jpg',true,false,10),
('spring-rolls','Spring Rolls','entradas',92,'4 piezas · Rellenos de vegetales, acompañados de salsa agridulce.','/assets/menu/spring-rolls.jpg',true,false,20),
('gyozas','Gyozas de cerdo','entradas',104,'5 piezas · Empanadillas fritas de cerdo con vegetales, acompañadas de salsa spicy ponzu.','/assets/menu/gyozas.jpg',false,false,30),
('rokka','Camarones Rokka','entradas',168,'Camarón tempura, mayo chipotle, cebollín y aguacate sobre cama de ensalada.','/assets/menu/rokka.jpg',true,true,40),
('karaague','Chicken Karaague','entradas',112,'Pechuga marinada en soya, ajo y jengibre, con mayo chipotle y limón.','/assets/menu/karaague.jpg',false,false,50),
('tempura-verduras','Tempura de verduras','entradas',116,'4 piezas · Verduras de temporada tempurizadas.','/assets/menu/tempura-verduras.jpg',false,false,60),
('kushi-queso','Kushiague de queso manchego','kushiagues',106,'2 piezas · Brochetas empanizadas acompañadas de salsa kushiague.','/assets/menu/kushi-queso.jpg',false,false,70),
('misoshiro','Misoshiro','sopas',78,'225 ml · Fondo miso, harusame, wakame, cebollín y tofu.','/assets/menu/misoshiro.jpg',false,false,80),
('pork-belly-ramen','Pork Belly Ramen','ramen',206,'Pasta ramen, pork belly teriyaki, naruto, verduras, huevo, nori y fondo tonkotsu.','/assets/menu/pork-belly-ramen.jpg',true,false,90),
('tantan-ramen','Tantan Ramen','ramen',218,'Pasta ramen, carne de cerdo picante, chile tempura, huevo, espinaca y fondo tonkotsu.','/assets/menu/tantan-ramen.jpg',false,true,100),
('ebi-crispy-ramen','Ebi Crispy Ramen','ramen',236,'Pasta ramen, camarones crujientes, cebollín, huevo, jitomate, chilli oil y tonkotsu.','/assets/menu/ebi-crispy-ramen.jpg',true,true,110),
('sunset','Sunset','poke-bowl',196,'320 g · Salmón, atún, pescado blanco, aguacate, cebollín y mayo sriracha.','/assets/menu/sunset.jpg',false,false,120),
('tokio-bacon','Tokio Bacon','poke-bowl',186,'320 g · Salmón, tocino ahumado, aguacate, queso fila, pepino y mayo habanero.','/assets/menu/tokio-bacon.jpg',false,false,130),
('samurai','Samurai','poke-bowl',182,'320 g · Camarones rokka, mango, col morada, aguacate y mayo chipotle.','/assets/menu/samurai.jpg',false,false,140),
('spicy-tuna-roll','Spicy Tuna Roll','rollos',154,'10 piezas · Tempurizado, nori, salsa de anguila, cebollín, aguacate y atún spicy.','/assets/menu/spicy-tuna-roll.jpg',true,true,150),
('tampico-roll','Tampico Roll','rollos',148,'10 piezas · Empanizado, tampico, salsa kushiague, aguacate y pepino.','/assets/menu/tampico-roll.jpg',false,false,160),
('philly-roll','Philly Roll','rollos',162,'10 piezas · Empanizado, salsa de anguila, salmón, pepino y queso.','/assets/menu/philly-roll.jpg',false,false,170),
('crunch-roll','Crunch Roll','rollos',172,'10 piezas · Salmón, mayo chipotle, kakiage, queso crema y aguacate.','/assets/menu/crunch-roll.jpg',false,false,180),
('gohan-kyo','Gohan Kyo','arroz',108,'320 g · Gohan, tampico, aguacate, mango, kanikama tempura, chipotle y anguila.','/assets/menu/gohan-kyo.jpg',false,false,190),
('cheesecake-japones','Cheese Cake Japonés','postres',126,'Individual · Con helado de vainilla y salsa de frutos rojos.','/assets/menu/cheesecake-japones.jpg',false,false,200)
)
insert into public.products(slug,name,category_id,price,description,image_url,featured,spicy,sort_order)
select s.slug,s.name,c.id,s.price,s.description,s.image_url,s.featured,s.spicy,s.sort_order
from seed s join public.categories c on c.slug=s.cat
on conflict (slug) do update set
name=excluded.name, category_id=excluded.category_id, price=excluded.price, description=excluded.description,
image_url=excluded.image_url, featured=excluded.featured, spicy=excluded.spicy, sort_order=excluded.sort_order;

-- IMPORTANTE: crea el usuario administrador en Authentication > Users y después ejecuta:
-- update public.profiles set is_admin = true where id = (select id from auth.users where email = 'admin@tudominio.com');
