import React, { useEffect, useState } from 'react'
import { RefreshCw, ChefHat, LogOut, Clock3, MapPin, Bike, Store, Check, ArrowRight } from 'lucide-react'
import { supabase } from '../supabase'

const money=n=>`$${Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:2})}`
const branchName=id=>id==='zakia'?'KYO Zákia':'KYO Milenio'

export function KitchenGate({auth,children}){
  if(auth.loading)return <main className="kitchen-login"><RefreshCw className="spin"/><p>Comprobando acceso...</p></main>
  if(!auth.user)return <KitchenLogin/>
  if(!auth.profile?.kitchen_branch && !auth.profile?.is_admin)return <main className="kitchen-login"><ChefHat size={48}/><h1>Cuenta sin sucursal de cocina</h1><p>Asigna <b>zakia</b> o <b>milenio</b> a esta cuenta desde Supabase.</p><button className="primary" onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></main>
  return children
}
function KitchenLogin(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError(error.message)};return <main className="kitchen-login"><form className="kitchen-login-card" onSubmit={submit}><ChefHat size={42}/><span>MODO COCINA</span><h1>KYO</h1><p>Entra con la cuenta de tu sucursal.</p><label>Correo<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="zakia@kyosushi.mx"/></label><label>Contraseña<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="form-message">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Entrando...':'Entrar a cocina'}</button></form></main>}

export function KitchenMode({auth}){
  const branch=auth.profile?.kitchen_branch||'zakia';const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true)
  const load=async()=>{if(!supabase)return;setLoading(true);let q=supabase.from('orders').select('*, order_items(*), profiles(full_name,phone)').eq('branch_id',branch).in('status',['preparing','ready','on_the_way']).order('created_at',{ascending:true});const {data}=await q;setOrders(data||[]);setLoading(false)}
  useEffect(()=>{load();if(!supabase)return;const ch=supabase.channel(`kitchen-${branch}`).on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:`branch_id=eq.${branch}`},load).subscribe();return()=>supabase.removeChannel(ch)},[branch])
  const setStatus=async(id,status)=>{await supabase.from('orders').update({status}).eq('id',id);load()}
  const preparing=orders.filter(o=>o.status==='preparing');const ready=orders.filter(o=>o.status==='ready');const route=orders.filter(o=>o.status==='on_the_way')
  return <main className="kitchen-shell"><header className="kitchen-head"><div><span>MODO COCINA</span><h1>{branchName(branch)}</h1><p>Los pedidos nuevos entran automáticamente a Preparando.</p></div><div><button onClick={load}><RefreshCw className={loading?'spin':''}/></button><button onClick={()=>supabase.auth.signOut()}><LogOut/></button></div></header><section className="kitchen-board"><KitchenColumn title="Preparando" count={preparing.length} orders={preparing} actionLabel="Marcar listo" actionIcon={<Check/>} onAction={id=>setStatus(id,'ready')}/><KitchenColumn title="Listos" count={ready.length} orders={ready} actionLabel="Salió a ruta" actionIcon={<Bike/>} onAction={id=>setStatus(id,'on_the_way')}/></section>{route.length>0&&<section className="route-strip"><div><span>EN CAMINO</span><strong>{route.length} pedido{route.length!==1?'s':''}</strong></div>{route.map(o=><button key={o.id} onClick={()=>setStatus(o.id,'delivered')}>#{String(o.order_number).padStart(4,'0')} · Marcar entregado <ArrowRight/></button>)}</section>}</main>
}
function KitchenColumn({title,count,orders,actionLabel,actionIcon,onAction}){return <section className="kitchen-column"><header><h2>{title}</h2><b>{count}</b></header><div className="kitchen-list">{orders.length===0?<div className="kitchen-empty">No hay pedidos aquí.</div>:orders.map(o=><KitchenTicket key={o.id} order={o} actionLabel={actionLabel} actionIcon={actionIcon} onAction={()=>onAction(o.id)}/>)}</div></section>}
function KitchenTicket({order,actionLabel,actionIcon,onAction}){return <article className="kitchen-ticket"><div className="ticket-top"><div><small>PEDIDO</small><h3>#{String(order.order_number).padStart(4,'0')}</h3></div><span><Clock3/> {new Date(order.created_at).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</span></div><div className="ticket-items">{order.order_items?.map(i=><div className="kitchen-item-detail" key={i.id}><div className="kitchen-product-line"><b>{i.quantity}×</b><strong>{i.product_name}</strong></div>{i.customizations?.length>0&&<div className="kitchen-customizations">{Object.entries(i.customizations.reduce((groups,c)=>{const title=c.template_name||c.group_name||c.customization_name||c.title||'Personalización';(groups[title]??=[]).push(c);return groups},{})).map(([title,rows])=><div className="kitchen-custom-group" key={title}><strong>{title}</strong>{rows.map((c,idx)=><span key={idx}>{c.label||c.option_name||c.name}{Number(c.quantity||1)>1?` ×${c.quantity}`:''}</span>)}</div>)}</div>}{i.item_note&&<div className="kitchen-item-note"><strong>Nota del cliente</strong><p>{i.item_note}</p></div>}</div>)}</div><div className="ticket-meta"><span>{order.fulfillment_type==='delivery'?<Bike/>:<Store/>}{order.fulfillment_type==='delivery'?'Delivery':'Pickup'}</span>{order.delivery_address&&<span><MapPin/>{order.delivery_address}</span>}{order.delivery_reference&&<p><b>Referencia:</b> {order.delivery_reference}</p>}{order.delivery_notes&&<p><b>Notas del pedido:</b> {order.delivery_notes}</p>}</div><div className="ticket-foot"><strong>{money(order.total)}</strong><button onClick={onAction}>{actionIcon}{actionLabel}</button></div></article>}
